jobs:
- deployment: marketplace
  displayName: publish marketplace
  environment: marketplace
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: terraform_extension
        - task: Npm@1
          displayName: install
          inputs:
            workingDir: $(Pipeline.Workspace)/terraform_extension  
        - task: Npm@1
          displayName: publish
          inputs:
            workingDir: $(Pipeline.Workspace)/terraform_extension
            command: custom
            customCommand: 'run publish -- -t $(marketplace_access_token)'