stages:
- stage: publish
  dependsOn: test
  variables:
    - group: env_prod
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/tags/*'))
  jobs:
  - template: publish_marketplace.yml