jobs:
- deployment: marketplace
  displayName: publish marketplace
  environment: marketplace
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: download terraform extension
          inputs: 
            artifact: terraform_extension
            path: $(terraform_extension_dir)
        - task: Npm@1
          displayName: install
          inputs:
            workingDir: $(terraform_extension_dir)  
        - task: Npm@1
          displayName: publish
          inputs:
            workingDir: $(terraform_extension_dir)
            command: custom
            # customCommand: 'run publish -- -t $(marketplace_access_token)'
            customCommand: 'run pack'